### ISSUE TITLE
Error: Wild type is not consistent with the sequence at the mutation location!

### ISSUE THREAD

**Issue by Yuiceee** [LiamT01/CTR#4]
hello, I recently encountered this problem when using my own data for testing, what is the cause and how should I correct it?

**Comment by LiamT01** [comment]
Hello,

This error occurred inside the function `positional_features` when running `get_features.py` to generate features. It was due to that, for a particular sequence in your data, the wild-type amino acid at the mutation location (`sequence[mutation_location]` in the above function) was not the same as the wild-type reported (the argument `wild` passed to the function).

For example, the following data will cause this error:

| position | wild_type | mutation | ... | sequence |
| :-----------: | :-----------: | :-----------: | :-----------: | :-----------: | 
| 3 | E | K | ... | MEKVYFLR |

where the actual wild-type amino acid at the mutation location (3) is K instead of the wild-type reported (E).

Please check if there are any such mismatches in your data.

**Comment by Yuiceee** [comment]
Thank you for you nice reply, but i have another problem when I use this method, it suggested that I was missing files in the data path. After checking, I found that there were no such files, nor did they exist in github. Do you have any suggestions ? 

> Traceback (most recent call last):
  File "eval.py", line 39, in <module>
    data.append(generate_one_vector(chain, loc, wild, mutant))
  File "CTR/get_features.py", line 278, in generate_one_vector
    mean = pd.read_csv(args.mean).to_numpy().flatten()
   FileNotFoundError: [Errno 2] No such file or directory: 'data/mean.csv'

**Comment by LiamT01** [comment]
Hello,

After generating features (`features.csv`), `get_features.py` also calculates the mean and std values of the features and writes them to files that are, by default, located in the same folder as `features.csv`. You can check `rawdata_config.py` for path configuration.

From the error message, it seems that you have not successfully run `get_features.py` prior to running `eval.py`. Therefore,  before evaluating your dataset, please run `get_features.py` first, as this will generate `features.csv`, `mean.csv`, and `std.csv`.
